name: Scottclark
favicon: null
layout_spectrum: 0.24362
typography_spectrum: 0.13716603117063642
title: 'Scott Clark - Design & Digital Creative'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#425d97'
    - '#050504'
    - '#8a9bbf'
    - '#9b271e'
  brandStrength: 0.6843454381451011
  lightness: 0.3698163637891412
  saturation: 0.8186474307440221
  rhythmicContrast: 0.25281491270288825
purpose: []
