name: Scottclark
favicon: null
layout_spectrum: 1
typography_spectrum: 0.66071
title: 'Scott Clark - Design & Digital Creative'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#333333'
    - '#000000'
    - '#ffffff'
    - '#6f6f6f'
    - '#9f9f9f'
  brandStrength: 1
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 1
purpose: []
