name: Scottclark
favicon: null
layout_spectrum: 0.24362
typography_spectrum: 0.66071
title: 'Scott Clark - Design & Digital Creative'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#333333'
    - '#000000'
    - '#ffffff'
    - '#6f6f6f'
    - '#9f9f9f'
  brandStrength: 1
  lightness: 0.3698163637891412
  saturation: 0.8186474307440221
  rhythmicContrast: 0.25281491270288825
purpose: []
