name: Scottclark
favicon: null
layout_spectrum: 0
typography_spectrum: 0.66071
title: 'Scott Clark - Design & Digital Creative'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#179353'
    - '#000000'
    - '#7fc3a0'
    - '#fbeb19'
    - '#10368d'
  brandStrength: 1
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 1
purpose: []
